spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
              filters:
                - name: JwtAuth

            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/user/**
              filters:
                - name: JwtAuth
  jwt:
    secret-key: SUPER_SECRET_KEY_FOR_JWT_SIGNING