server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-user
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
            - Path=/user
        - id: ms-auth
          uri: http://localhost:8082
          predicates:
            - Path=/auth

jwt:
  secret: SUPER_SECRET_KEY_FOR_JWT_SIGNING
