spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:postgresql://localhost:5432/sos-database
    username: postgres
    password: Postgres1234567890
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      .hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
